remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: SERMetric
description: SERMetric is an open-source library for evaluating how Easy-to-Read (E2R) a text is. It supports a wide variety of indexes and allows the user to easily combine them.
